language: generic 

sudo: required

services:
    - docker

before_install:
    - docker build -f -t brendon-stephens/docker-react-demo Dockerfile.dev . 

script:
    - docker run -e CI=true brendon-stephens/docker-react-demo npm run test -- --coverage